version: "3.5"

services:
  api01: &api
    image: rafaelleoni/rinha-de-backend-2024-q1:latest
    hostname: api01
    environment:
      - DB_URL=postgres://admin:123@db/rinha?sslmode=disable
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "75MB"

  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_URL=postgres://admin:123@db/rinha?sslmode=disable
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "75MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "1.1"
          memory: "325MB"

networks:
  default:
    driver: bridge
    name: rinha-de-backend-2024-q1
